spring.datasource.url=jdbc:h2:mem:bookingya
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Servlet settings
server.port=8080
server.servlet.context-path=/api

# Logging
logging.level.root=INFO
logging.level.com.project.bookingya=DEBUG
